name: Changelog

on:
  pull_request:
    types: [ opened ]
    branches: [ main ]

jobs:
  auto:
    name: Auto
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'develop' && !contains(github.event.head_commit.message, 'skip ci') }}
    env:
      RUNTIME_OS: linux
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

    - name: Prepare repository
      run: git fetch --depth 100 --tags

    - name: "Make changelong"
      run: |
        set -xe
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        label=$(gh pr view $pull_number --json labels --jq '.labels[].name|select(. == "release")')
        
        if [[ "release" == "$label" ]]; then
          git checkout $GITHUB_HEAD_REF
          git pull
          ./bin/auto changelog --verbose
          git push origin $GITHUB_HEAD_REF
          gh pr merge $pull_number --auto --merge
          echo The PR was merged
        fi
        
