name: CI

on:
  - push

jobs:
  test:
    name: Auto
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    continue-on-error: false
    strategy:
      matrix:
        php-versions: ["8.1"]
    env:
      RUNTIME_OS: linux
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare repository
      run: git fetch --unshallow --tags

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: pecl
        coverage: "none"

    - name: "Auto shipit"
      run: |
        ./bin/auto shipit

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        title: AWS Release
        branch: production
        base: main