name: CI

on:
  - push

jobs:
  test:
    name: Auto
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    continue-on-error: false
    strategy:
      matrix:
        php-versions: ["8.1"]
    env:
      RUNTIME_OS: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: pecl
        coverage: "none"

    - name: "Auto shipit"
      run: |
        ./bin/auto shipit